#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-efivar-soname0
Version  : 0.21
Release  : 1
URL      : https://github.com/rhinstaller/efivar/releases/download/0.21/efivar-0.21.tar.bz2
Source0  : https://github.com/rhinstaller/efivar/releases/download/0.21/efivar-0.21.tar.bz2
Summary  : Tools to manage UEFI variables
Group    : Development/Tools
License  : LGPL-2.1
Requires: compat-efivar-soname0-bin
Requires: compat-efivar-soname0-lib
Requires: compat-efivar-soname0-doc
BuildRequires : popt-dev
Patch1: build.patch
Patch2: nvme.patch

%description
efivar provides a simple command line interface to the UEFI variable facility.

%package bin
Summary: bin components for the compat-efivar-soname0 package.
Group: Binaries

%description bin
bin components for the compat-efivar-soname0 package.


%package dev
Summary: dev components for the compat-efivar-soname0 package.
Group: Development
Requires: compat-efivar-soname0-lib
Requires: compat-efivar-soname0-bin
Provides: compat-efivar-soname0-devel

%description dev
dev components for the compat-efivar-soname0 package.


%package doc
Summary: doc components for the compat-efivar-soname0 package.
Group: Documentation

%description doc
doc components for the compat-efivar-soname0 package.


%package lib
Summary: lib components for the compat-efivar-soname0 package.
Group: Libraries

%description lib
lib components for the compat-efivar-soname0 package.


%prep
%setup -q -n efivar-0.21
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1494609184
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1494609184
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/efivar

%files dev
%defattr(-,root,root,-)
/usr/include/efivar/efiboot-creator.h
/usr/include/efivar/efiboot-loadopt.h
/usr/include/efivar/efiboot.h
/usr/include/efivar/efivar-dp.h
/usr/include/efivar/efivar-guids.h
/usr/include/efivar/efivar.h
/usr/lib64/libefiboot.so
/usr/lib64/libefivar.so
/usr/lib64/pkgconfig/efiboot.pc
/usr/lib64/pkgconfig/efivar.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libefiboot.so.0
/usr/lib64/libefiboot.so.0.21
/usr/lib64/libefivar.so.0
/usr/lib64/libefivar.so.0.21
