#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-efivar-soname0
Version  : 0.21
Release  : 10
URL      : https://github.com/rhinstaller/efivar/releases/download/0.21/efivar-0.21.tar.bz2
Source0  : https://github.com/rhinstaller/efivar/releases/download/0.21/efivar-0.21.tar.bz2
Summary  : Tools to manage UEFI variables
Group    : Development/Tools
License  : LGPL-2.1
Requires: compat-efivar-soname0-lib = %{version}-%{release}
Requires: compat-efivar-soname0-license = %{version}-%{release}
BuildRequires : popt-dev
# Suppress generation of debuginfo
%global debug_package %{nil}
Patch1: build.patch
Patch2: nvme.patch

%description
efivar provides a simple command line interface to the UEFI variable facility.

%package lib
Summary: lib components for the compat-efivar-soname0 package.
Group: Libraries
Requires: compat-efivar-soname0-license = %{version}-%{release}

%description lib
lib components for the compat-efivar-soname0 package.


%package license
Summary: license components for the compat-efivar-soname0 package.
Group: Default

%description license
license components for the compat-efivar-soname0 package.


%prep
%setup -q -n efivar-0.21
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567808091
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1567808091
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-efivar-soname0
cp COPYING %{buildroot}/usr/share/package-licenses/compat-efivar-soname0/COPYING
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/efivar
rm -f %{buildroot}/usr/include/efivar/efiboot-creator.h
rm -f %{buildroot}/usr/include/efivar/efiboot-loadopt.h
rm -f %{buildroot}/usr/include/efivar/efiboot.h
rm -f %{buildroot}/usr/include/efivar/efivar-dp.h
rm -f %{buildroot}/usr/include/efivar/efivar-guids.h
rm -f %{buildroot}/usr/include/efivar/efivar.h
rm -f %{buildroot}/usr/lib64/libefiboot.so
rm -f %{buildroot}/usr/lib64/libefivar.so
rm -f %{buildroot}/usr/lib64/pkgconfig/efiboot.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/efivar.pc
rm -f %{buildroot}/usr/share/man/man1/efivar.1
rm -f %{buildroot}/usr/share/man/man3/efi_append_variable.3
rm -f %{buildroot}/usr/share/man/man3/efi_del_variable.3
rm -f %{buildroot}/usr/share/man/man3/efi_get_next_variable_name.3
rm -f %{buildroot}/usr/share/man/man3/efi_get_variable.3
rm -f %{buildroot}/usr/share/man/man3/efi_get_variable_attributes.3
rm -f %{buildroot}/usr/share/man/man3/efi_get_variable_size.3
rm -f %{buildroot}/usr/share/man/man3/efi_guid_to_id_guid.3
rm -f %{buildroot}/usr/share/man/man3/efi_guid_to_name.3
rm -f %{buildroot}/usr/share/man/man3/efi_guid_to_str.3
rm -f %{buildroot}/usr/share/man/man3/efi_guid_to_symbol.3
rm -f %{buildroot}/usr/share/man/man3/efi_name_to_guid.3
rm -f %{buildroot}/usr/share/man/man3/efi_set_variable.3
rm -f %{buildroot}/usr/share/man/man3/efi_str_to_guid.3
rm -f %{buildroot}/usr/share/man/man3/efi_symbol_to_guid.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_alloc.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_export.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_free.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_get_attributes.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_get_data.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_get_guid.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_get_name.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_import.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_realize.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_set_attributes.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_set_data.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_set_guid.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_set_name.3
rm -f %{buildroot}/usr/share/man/man3/efi_variable_t.3
rm -f %{buildroot}/usr/share/man/man3/efi_variables_supported.3

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libefiboot.so.0
/usr/lib64/libefiboot.so.0.21
/usr/lib64/libefivar.so.0
/usr/lib64/libefivar.so.0.21

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-efivar-soname0/COPYING
